-- Crear usuario C##py02
CREATE USER C##py02 IDENTIFIED BY "123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Dar todos los permisos necesarios
GRANT CONNECT, RESOURCE, DBA TO C##py02;
GRANT CREATE SESSION TO C##py02;
GRANT UNLIMITED TABLESPACE TO C##py02;

COMMIT;
